// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://unghfseexveyrqlbksle.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVuZ2hmc2VleHZleXJxbGJrc2xlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM3NzU1NDksImV4cCI6MjA1OTM1MTU0OX0.tQDWIVg9e5JksQt30LkeTFyZBhC5vWl62w_zCYbNPsM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);